version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y wget
      - wget -O kotlin-compiler.zip https://github.com/JetBrains/kotlin/releases/download/v1.8.22/kotlin-compiler-1.8.22.zip
      - unzip kotlin-compiler.zip -d /opt
  build:
    commands:
      - mvn compile
      - mvn test
      - mvn install
  post_build:
    commands:
      - mvn package
      - mv target/cicdapp-dvj-0.0.1-SNAPSHOT.jar root.jar

reports:
  jacoco-report:
    files:
      - 'target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
  junit-report:
    files:
      - 'target/surefire-reports/*.xml'
    file-format: 'JUNITXML'

artifacts:
  files:
    - root.jar
